<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Translation\Translator;
use JsonException;

class LangFrontendExportCommand extends Command
{
    /**
     * Locales bundled into the SPA.
     */
    private const array LOCALES = ['en', 'ru', 'uk'];

    /**
     * Game sections actually consumed by the frontend bundle.
     * Extend this list (and re-run the command) when the SPA starts using
     * translations from another section.
     */
    private const array FRONTEND_GAME_SECTIONS = ['ADN', 'BUI', 'LAB', 'RES', 'SPE'];

    protected $signature = 'tso:lang:export-frontend
        {--output-dir= : Override the output directory (used by tests)}';

    protected $description = 'Export UI + game translations to resources/js/lang/generated/<locale>.json for the SPA bundle';

    /**
     * @throws JsonException
     */
    public function handle(Translator $translator): int
    {
        $outputDirectory = (string) ($this->option('output-dir') ?: resource_path('js/lang/generated'));

        if (! is_dir($outputDirectory) && ! mkdir($outputDirectory, 0755, true) && ! is_dir($outputDirectory)) {
            $this->error("Unable to create output directory: {$outputDirectory}");

            return self::FAILURE;
        }

        $rawPayloads = [];

        foreach (self::LOCALES as $locale) {
            $ui = $translator->get('ui', [], $locale, false);
            $ui = is_array($ui) ? $ui : [];

            $gameCatalog = $translator->get('game', [], $locale, false);
            $gameCatalog = is_array($gameCatalog) ? $gameCatalog : [];

            $game = [];

            foreach (self::FRONTEND_GAME_SECTIONS as $section) {
                $entries = $gameCatalog[$section] ?? [];
                $game[$section] = is_array($entries) ? $entries : [];
            }

            $tasks = $translator->get('tasks', [], $locale, false);
            $tasks = is_array($tasks) ? $tasks : [];

            $rawPayloads[$locale] = [
                'game' => $game,
                'tasks' => $tasks,
                'ui' => $ui,
            ];
        }

        $enPayload = $rawPayloads['en'];

        foreach (self::LOCALES as $locale) {
            if ($locale !== 'en') {
                $rawPayloads[$locale] = $this->fillMissingKeys($rawPayloads[$locale], $enPayload);
            }

            $payload = array_merge([
                '_generated' => 'DO NOT EDIT. Generated by "php artisan tso:lang:export-frontend".',
            ], $this->sortRecursive($rawPayloads[$locale]), [
                'locale' => $locale,
            ]);

            $json = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)."\n";
            $target = rtrim($outputDirectory, '/')."/{$locale}.json";
            $temporary = $target.'.tmp.'.getmypid();

            if (file_put_contents($temporary, $json) === false || ! rename($temporary, $target)) {
                @unlink($temporary);
                $this->error("Unable to write {$target}");

                return self::FAILURE;
            }

            $this->info("Wrote {$target}");
        }

        return self::SUCCESS;
    }

    /**
     * @param  array<string, mixed>  $target
     * @param  array<string, mixed>  $source
     * @return array<string, mixed>
     */
    private function fillMissingKeys(array $target, array $source): array
    {
        foreach ($source as $key => $value) {
            if (! array_key_exists($key, $target)) {
                $target[$key] = $value;
            } elseif (is_array($value) && is_array($target[$key])) {
                $target[$key] = $this->fillMissingKeys($target[$key], $value);
            }
        }

        return $target;
    }

    /**
     * @param  array<string, mixed>  $array
     * @return array<string, mixed>
     */
    private function sortRecursive(array $array): array
    {
        ksort($array, SORT_STRING);

        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $array[$key] = $this->sortRecursive($value);
            }
        }

        return $array;
    }
}
